name: Refresh website from Google Sheet

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cloudflare Deploy
        run: curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"